DROP TABLE IF EXISTS message;

CREATE TABLE message (
	'id' INTEGER PRIMARY KEY AUTOINCREMENT,
	'creator' TEXT NOT NULL,
	'text' TEXT NOT NULL,
	'created' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
